backend:
  name: git-gateway
  branch: main  # اسم الفرع بتاعك على GitHub

media_folder: "images/uploads" # المكان اللي الصور هتتحفظ فيه
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "data/projects"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }