backend:
  name: beshofocus204
  repo: besho-portfolio # استبدل ببياناتك
  branch: main

media_folder: "projects/images"
public_folder: "/projects/images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects/data"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Project Image", name: "image", widget: "image" }
