backend:
  name: git-gateway
  branch: main # تأكد إن ده اسم البرانش بتاعك

local_backend: true # عشان لو حبيت تجربه على جهازك

media_folder: "projects/images"
public_folder: "/projects/images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects/data"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Project Image", name: "image", widget: "image" }
